workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: "3.22.2"  # Versão entre aspas
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  # Seu Key ID GA6U2S4T39
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
