workflows:
  ios-build-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      groups:
        # Grupo com as credenciais da App Store Connect API Key
        # e a variável MATCH_SSH_PRIVATE_KEY
        - appstore_credentials 
      vars:
        # Variáveis BUNDLE_ID e TEAM_ID serão lidas pelo Fastfile a partir do ambiente
        BUNDLE_ID: "app.telecris"
        TEAM_ID: "QRUFZ86NTH"

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane
      
      - name: Set up SSH key for Git
        script: |
          echo "Setting up SSH key file for Git..."
          mkdir -p ~/.ssh
          echo "$MATCH_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519_match_git
          chmod 600 ~/.ssh/id_ed25519_match_git
          echo "Adding GitHub to known hosts..."
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          echo "Exporting GIT_SSH_COMMAND to force key usage..."
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_match_git -o IdentitiesOnly=yes"

      - name: Run Fastlane Sync Signing Lane
        script: |
          echo "Running Fastlane lane to sync signing assets..."
          # Executa a lane 'sync_signing' definida no Fastfile
          # O Fastfile deve estar na pasta 'fastlane' do projeto
          cd fastlane && fastlane sync_signing
          # Se o Fastfile estiver na raiz, remova o 'cd fastlane &&'

      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Export IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $CM_BUILD_DIR

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY 
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

