workflows:
  ios-build-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      groups:
        # Grupo com as credenciais da App Store Connect API Key
        # e também a variável CERT_REPO_SSH_KEY
        - appstore_credentials 
      vars:
        # Variáveis necessárias para o Fastlane match
        BUNDLE_ID: "app.telecris"
        APPLE_ID: "sac@telecris.app" # Email da conta Apple Developer
        TEAM_ID: "QRUFZ86NTH" # Seu Team ID da Apple

    scripts:
      - name: Set up SSH key for Git
        script: |
          echo "Setting up SSH key..."
          set -e # Exit immediately if a command exits with a non-zero status.
          mkdir -p ~/.ssh
          # Decodifica a chave privada da variável de ambiente
          echo "$CERT_REPO_SSH_KEY" | base64 --decode > ~/.ssh/id_ed25519_cert_repo
          chmod 600 ~/.ssh/id_ed25519_cert_repo
          eval "$(ssh-agent -s)" # Start ssh-agent
          ssh-add ~/.ssh/id_ed25519_cert_repo
          # Add GitHub to known hosts to avoid prompt
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "SSH key setup complete."
      - name: Install Fastlane
        script: |
          gem install fastlane
      - name: Set up code signing with Fastlane (using SSH)
        script: |
          # Usa SSH para autenticação
          fastlane match appstore \
            --app_identifier "$BUNDLE_ID" \
            --username "$APPLE_ID" \
            --team_id "$TEAM_ID" \
            --git_url "git@github.com:dannwagner/certificates-repo.git" \
            --readonly # Mantenha se o match só precisa ler. Remova se precisar escrever.
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Export IPA
        script: |
          # Verifique se ios/exportOptions.plist está correto (nomes de certificado/perfil)
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $CM_BUILD_DIR

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        # --- Configurações Opcionais --- 
        # submit_to_testflight: true
        # beta_groups: 
        #   - NomeDoGrupoBeta
        # submit_to_app_store: false

