workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - ios_config
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
    scripts:
      # Pré-requisitos
      - flutter pub get
      
      # Configuração iOS (comandos que você pediu)
      - cd ios
      - pod install
      - cd ..
      
      # Build iOS
      - flutter build ios --release --no-codesign
      
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        auth: integration # Usa integração com App Store Connect
        apple_id: $APP_STORE_CONNECT_EMAIL
        app_specific_password: $APP_SPECIFIC_PASSWORD
      email:
        recipients:
          - seu_email@exemplo.com
