workflows:
  ios-build-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      groups:
        # Grupo com as credenciais da App Store Connect API Key
        # e a variável MATCH_SSH_PRIVATE_KEY (com a NOVA chave privada em TEXTO PLANO)
        - appstore_credentials 
      vars:
        # Variáveis necessárias para o Fastlane match
        BUNDLE_ID: "app.telecris"
        APPLE_ID: "sac@telecris.app" # Email da conta Apple Developer
        TEAM_ID: "QRUFZ86NTH" # Seu Team ID da Apple

    scripts:
      # O script "Set up SSH key for Git (using printf)" foi REMOVIDO
      - name: Install Fastlane
        script: |
          gem install fastlane
      - name: Set up code signing with Fastlane (using SSH)
        script: |
          echo "Adding GitHub to known hosts..."
          # Garante que o host do GitHub é conhecido
          mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "Running fastlane match..."
          # Usa SSH para autenticação (Fastlane deve pegar MATCH_SSH_PRIVATE_KEY automaticamente)
          # A flag --readonly foi REMOVIDA anteriormente
          fastlane match appstore \
            --app_identifier "$BUNDLE_ID" \
            --username "$APPLE_ID" \
            --team_id "$TEAM_ID" \
            --git_url "git@github.com:dannwagner/certificates-repo.git" \
            --verbose # Mantém verbose para logs detalhados
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Export IPA
        script: |
          # Verifique se ios/exportOptions.plist está correto (nomes de certificado/perfil)
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $CM_BUILD_DIR

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        # --- Configurações Opcionais --- 
        # submit_to_testflight: true
        # beta_groups: 
        #   - NomeDoGrupoBeta
        # submit_to_app_store: false

