workflows:
  ios-build-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      groups:
        # Grupo com as credenciais da App Store Connect API Key
        # e a variável MATCH_SSH_PRIVATE_KEY
        - appstore_credentials 
      vars:
        BUNDLE_ID: "app.telecris"
        TEAM_ID: "QRUFZ86NTH"

    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane
      
      - name: Set up code signing with Fastlane (explicit API Key)
        script: |
          echo "Setting up SSH key file for Git..."
          mkdir -p ~/.ssh
          echo "$MATCH_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519_match_git
          chmod 600 ~/.ssh/id_ed25519_match_git
          echo "Adding GitHub to known hosts..."
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          echo "Exporting GIT_SSH_COMMAND to force key usage..."
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_match_git -o IdentitiesOnly=yes"
          
          echo "Running fastlane match explicitly using App Store Connect API Key..."
          # Passando explicitamente os parâmetros da API Key para o fastlane match
          fastlane match appstore \
            --app_identifier "$BUNDLE_ID" \
            --team_id "$TEAM_ID" \
            --git_url "git@github.com:dannwagner/certificates-repo.git" \
            --api_key_id "$APP_STORE_CONNECT_KEY_ID" \
            --api_issuer_id "$APP_STORE_CONNECT_ISSUER_ID" \
            --api_key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --verbose 
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Export IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $CM_BUILD_DIR

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY 
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

