workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - ios_config
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        api_key: $APP_STORE_CONNECT_API_KEY  # Chave API (não é o email)
