workflows:
  ios-build-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "app.telecris"
        APPLE_ID: "sac@telecris.app"
        TEAM_ID: "QRUFZ86NTH"
        APP_STORE_CONNECT_KEY_ID: "GA6U2S4T39"
        APP_STORE_CONNECT_ISSUER_ID: "a1a19791-db1b-49fc-880a-d2716093d677"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APPLE_APP_ID: "6743127054"
        APP_SKU: "TELECRIS.APP"
    scripts:
      - name: Install Fastlane
        script: |
          gem install fastlane
      - name: Set up code signing with Fastlane
        script: |
          fastlane match appstore \
            --app_identifier "app.telecris" \
            --username "$APPLE_ID" \
            --team_id "$TEAM_ID" \
            --git_url "https://github.com/dannwagner/certificates-repo.git" \
            --git_basic_authorization $(echo -n "dannwagner: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" | base64)
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Export IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Runner.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: true  # Remove essa linha se você só quer enviar pro TestFlight
