name: Setup iOS
on: [workflow_dispatch]
jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter create --platforms ios .
      - run: |
          cd ios
          pod install
          cd ..
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add --all
          git commit -m "Add iOS files"
          git push
