name: Simple iOS Setup
on: [workflow_dispatch]

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - run: sudo gem install cocoapods
      
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - run: |
          flutter create --platforms ios .
          cd ios
          pod install
          cd ..
          git add .
          git commit -m "Added iOS files" || true
          git push
